import React, { useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { artworks } from '../model';
import { images } from '../assets';
import { useStore } from '../store';
import { ArtCard, Button, CircleButton, Empty, Eyebrow, Icon, Page, Section, T, Title, c, s, serif, useRootNavigation } from '../ui';

export function DiscoverScreen() {
  const nav = useRootNavigation(); const { state } = useStore();
  const [query, setQuery] = useState(''), [category, setCategory] = useState('All works');
  const filtered = artworks.filter(a => (category === 'All works' || a.category === category) && `${a.title} ${a.artist} ${a.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase().trim()));
  return <Page><View style={s.rowBetween}><View style={s.row}><Image source={require('../../assets/icon.png')} style={styles.logo}/><T style={styles.wordmark}>unframe.</T></View><CircleButton name="scan-outline" label="Find an artwork" onPress={() => nav.navigate('Lookup')}/></View><View style={{ gap: 7 }}><T style={s.small}>A good day to discover, {state.preferences.name}.</T><Title>Your next perspective.</Title></View><View style={styles.search}><Icon name="search-outline" size={19} color={c.muted}/><TextInput accessibilityLabel="Search artworks" value={query} onChangeText={setQuery} placeholder="An artwork, an artist, a little inspiration…" placeholderTextColor={c.muted} style={styles.searchInput} returnKeyType="search" clearButtonMode="while-editing"/></View>
  {!query && <><View style={styles.hero}><View style={styles.heroCopy}><Eyebrow>A little curiosity goes a long way</Eyebrow><T style={styles.heroTitle}>Follow your{`\n`}<T style={[styles.heroTitle, styles.heroEm]}>curiosity.</T></T><T style={[s.muted, { fontSize: 12 }]}>A work that stops you. A story that stays.{`\n`}Find your own way through the museum.</T><Button title="Plan my visit" icon="arrow-forward" onPress={() => nav.navigate('Planner')} style={{ alignSelf: 'flex-start', marginTop: 5 }}/></View><Pressable accessibilityRole="button" accessibilityLabel="Featured artwork Riverlight" onPress={() => nav.navigate('Artwork', { id: 'riverlight' })}><Image source={images.riverlight} style={styles.heroImage}/><View style={styles.caption}><View><T style={styles.captionTitle}>Riverlight</T><T style={styles.captionMeta}>Elena Marr, 2024 · Ways of Seeing</T></View><Icon name="arrow-up-outline" color="white"/></View></Pressable></View><Pressable accessibilityRole="button" accessibilityLabel="Explore Northbank Gallery" style={styles.museum} onPress={() => nav.navigate('Home', { screen: 'Explore' })}><View style={styles.museumIcon}><Icon name="business-outline" color={c.muted}/></View><View style={{ flex: 1 }}><T style={s.label}>Northbank Gallery</T><T style={s.small}>Sample museum · 5 rooms to explore</T></View><Icon name="arrow-forward" size={18}/></Pressable></>}
  <Section title={query ? `${filtered.length} discoveries` : 'Catch your eye'} action={query ? undefined : 'Explore all'} onAction={() => nav.navigate('Home', { screen: 'Explore' })}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{['All works', 'Painting', 'Sculpture', 'Print', 'Drawing', 'Installation'].map(value => <Pressable key={value} accessibilityRole="button" accessibilityState={{ selected: category === value }} onPress={() => setCategory(value)} style={[s.chip, category === value && s.chipActive]}><T style={[s.chipText, category === value && { color: c.white }]}>{value}</T></Pressable>)}</ScrollView><View style={s.grid}>{filtered.map(art => <ArtCard key={art.id} art={art}/>)}</View>{!filtered.length && <Empty title="A different starting point?" body="Try an artist, an artwork title, or an interest like nature."/>}<View style={[s.card, { backgroundColor: c.sand }]}><Icon name="compass-outline" size={30} color={c.muted}/><T style={s.sectionTitle}>A visit that feels like you.</T><T style={s.muted}>Your interests. Your pace. A little room for the unexpected.</T><Button title="Make it personal" secondary icon="arrow-forward" onPress={() => nav.navigate('Planner')}/></View><Pressable accessibilityRole="button" onPress={() => nav.navigate('About')} style={s.linkTouch}><T style={[s.small, { textAlign: 'center' }]}>Made for curiosity · About this prototype ↗</T></Pressable></Page>;
}
const styles = StyleSheet.create({
  logo: { width: 29, height: 29, borderRadius: 8 }, wordmark: { fontSize: 27, lineHeight: 33, fontWeight: '700', letterSpacing: -1.4 }, search: { flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: c.border, borderRadius: 12, paddingHorizontal: 13, backgroundColor: c.white }, searchInput: { flex: 1, minHeight: 46, fontSize: 11, color: c.ink }, hero: { backgroundColor: c.sage, borderRadius: 18, overflow: 'hidden' }, heroCopy: { padding: 25, gap: 15 }, heroTitle: { fontFamily: serif, fontSize: 45, lineHeight: 49, letterSpacing: -1.8 }, heroEm: { color: '#7A896A', fontStyle: 'italic' }, heroImage: { width: '100%', height: 220 }, caption: { position: 'absolute', bottom: 15, left: 15, right: 15, padding: 13, backgroundColor: '#273A31B8', borderRadius: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, captionTitle: { color: c.white, fontFamily: serif, fontSize: 19, lineHeight: 24 }, captionMeta: { color: '#ECEEDD', fontSize: 10, lineHeight: 17 }, museum: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingBottom: 20, borderBottomWidth: 1, borderColor: c.border }, museumIcon: { width: 42, height: 42, borderRadius: 10, backgroundColor: c.sand, alignItems: 'center', justifyContent: 'center' }
});
