import React, { useState } from 'react';
import { Image, Pressable, StyleSheet, View } from 'react-native';
import { artwork, sampleArtworks as artworks } from '../model';
import { images } from '../assets';
import { useStore } from '../store';
import { makeReflection } from '../state';
import { ArtRow, Button, Chip, Eyebrow, Icon, Notice, Page, Section, T, Title, c, s, serif, useRootNavigation } from '../ui';

export function ExploreScreen() {
  const nav = useRootNavigation(); const { state, dispatch } = useStore();
  const [room, setRoom] = useState<string | null>(null), [reflection, setReflection] = useState('');
  const tour = state.tour;
  const labels: Record<string, string> = { '01': 'Landscape', '02': 'Sculpture', '03': 'Colour & form', '04': 'Nature', '05': 'Installation' };
  const roomButton = (id: string) => <Pressable key={id} accessibilityRole="button" accessibilityLabel={`Room ${id}, ${labels[id]}${id === '05' ? ', stairs required' : ''}`} accessibilityState={{ selected: room === id }} onPress={() => setRoom(room === id ? null : id)} style={[styles.room, id === '05' && styles.stairs, room === id && styles.selected]}><T style={styles.roomNumber}>{id}</T><T style={styles.roomLabel}>{labels[id]}</T><Icon name={id === '05' ? 'walk-outline' : 'image-outline'} size={16} color={c.muted}/></Pressable>;
  function finish() { if (!tour?.completed.length) return; const visit = makeReflection(tour.completed, artworks); dispatch({ type: 'finish', visit }); if (state.preferences.saveHistory) nav.navigate('Home', { screen: 'Saved' }); else setReflection(visit.summary); }
  return <Page><Eyebrow>Northbank Gallery · Sample museum</Eyebrow><Title>Find your own way.</Title><T style={s.muted}>A little direction. Plenty of room to wander.</T><Button title={tour ? 'Adjust my tour' : 'Plan my visit'} icon="compass-outline" onPress={() => nav.navigate('Planner')}/>{reflection && <View style={s.card}><T style={s.sectionTitle}>A moment to reflect.</T><T>{reflection}</T><Notice>Visit history is off. This reflection has not been saved.</Notice><Button title="Close reflection" secondary onPress={() => setReflection('')}/></View>}
  {tour && <View style={s.card}><Section title="Your route, your rhythm"/><T style={s.small}>{tour.artworkIds.length} stops · About {tour.minutes} min · {tour.completed.length} explored</T>{tour.stepFree && <Notice icon="accessibility-outline">Step-free route · Rooms without stairs</Notice>}{tour.artworkIds.map((id, index) => { const art = artwork(id)!; const done = tour.completed.includes(id), skip = tour.skipped.includes(id); return <View key={id} style={[styles.stop, skip && { opacity: .6 }]}><View style={s.row}><View style={[styles.step, done && { backgroundColor: c.green }]}>{done ? <Icon name="checkmark" size={15} color="white"/> : <T style={s.small}>{index + 1}</T>}</View><Image source={images[id]} style={styles.stopImage}/><Pressable accessibilityRole="button" accessibilityLabel={`View ${art.title}`} style={{ flex: 1 }} onPress={() => nav.navigate('Artwork', { id })}><T style={s.artTitle}>{art.title}</T><T style={s.small}>Room {art.room} · {art.minutes} min{skip ? ' · Skipped' : ''}</T></Pressable></View><View style={[s.row, { justifyContent: 'flex-end' }]}><Pressable accessibilityRole="button" accessibilityLabel={`${skip ? 'Restore' : 'Skip'} ${art.title}`} style={s.linkTouch} onPress={() => dispatch({ type: 'stop', id, status: 'skipped' })}><T style={s.link}>{skip ? 'Restore' : 'Skip'}</T></Pressable><Chip label={done ? 'Explored ✓' : 'Mark explored'} active={done} onPress={() => dispatch({ type: 'stop', id, status: 'completed' })}/></View></View>; })}<Button title="Finish my visit" icon="checkmark" disabled={!tour.completed.length} onPress={finish}/><Button title="End without saving" secondary onPress={() => dispatch({ type: 'end' })}/></View>}
  <Section title="The gallery, at a glance"/><View style={styles.map}><View style={styles.rooms}>{['01', '02', '03'].map(roomButton)}</View><T style={styles.walkway}>GALLERY WALKWAY</T><View style={styles.rooms}>{roomButton('04')}<View style={styles.entrance}><Icon name="enter-outline" color={c.muted}/><T style={styles.roomLabel}>Entrance</T></View>{roomButton('05')}</View></View><Notice>Illustrative floor plan. Tap a room to explore. Live indoor positioning is not connected.</Notice><Section title={room ? `Inside Room ${room}` : 'Around the gallery'} action={room ? 'Show all' : undefined} onAction={() => setRoom(null)}/><View>{artworks.filter(a => !room || a.room === room).map(art => <ArtRow key={art.id} art={art}/>)}</View></Page>;
}
const styles = StyleSheet.create({
  map: { backgroundColor: '#EFF2E7', padding: 15, borderRadius: 16, borderWidth: 1, borderColor: c.border }, rooms: { flexDirection: 'row', gap: 8 }, room: { flex: 1, minHeight: 112, backgroundColor: '#DFE7D5', borderWidth: 1, borderColor: '#CDD9BF', borderRadius: 10, alignItems: 'center', justifyContent: 'center', gap: 5 }, selected: { borderColor: c.green, borderWidth: 2, backgroundColor: '#CBD9BD' }, stairs: { backgroundColor: '#E9DFD1', borderColor: '#D4C7B6' }, roomNumber: { fontFamily: serif, fontSize: 28, lineHeight: 34, color: '#59724B' }, roomLabel: { fontSize: 9, lineHeight: 14, color: c.muted, textAlign: 'center' }, walkway: { textAlign: 'center', fontSize: 8, lineHeight: 36, letterSpacing: 2, color: c.muted }, entrance: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 8 }, stop: { paddingVertical: 10, gap: 9, borderTopWidth: 1, borderColor: c.border }, step: { width: 25, height: 25, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: c.sage }, stopImage: { width: 40, height: 48, borderRadius: 6 }
});
