import React, { useEffect, useRef, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import type { BottomTabScreenProps } from '@react-navigation/bottom-tabs';
import { artworks, artwork, type TabParams } from '../model';
import { guideReply, type GuideSource } from '../../../shared/domain.js';
import { CircleButton, Eyebrow, Icon, Notice, T, Title, c, s, useRootNavigation } from '../ui';

interface Message { role: 'user' | 'guide'; text: string; sources?: GuideSource[] }
export function GuideScreen({ route, navigation }: BottomTabScreenProps<TabParams, 'Guide'>) {
  const nav = useRootNavigation(); const [messages, setMessages] = useState<Message[]>([]), [question, setQuestion] = useState(''), [focus, setFocus] = useState<string | undefined>();
  const scroll = useRef<ScrollView>(null);
  function ask(text: string, artworkId = focus) {
    if (!text.trim()) return;
    const reply = guideReply(text.trim(), artworks, artworkId);
    setMessages(previous => [...previous, { role: 'user', text: text.trim() }, { role: 'guide', text: reply.text, sources: reply.sources }]);
    setQuestion('');
  }
  useEffect(() => {
    const id = route.params?.artworkId;
    if (id && artwork(id)) { setFocus(id); ask(`Tell me about ${artwork(id)!.title}`, id); navigation.setParams({ artworkId: undefined }); }
  }, [route.params?.artworkId]);
  return <SafeAreaView edges={['top']} style={s.safe}><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.header}><View style={s.rowBetween}><Eyebrow>A conversation with the collection</Eyebrow><CircleButton name="refresh-outline" label="New conversation" onPress={() => { setMessages([]); setFocus(undefined); }}/></View><Title>Curiosity looks good{`\n`}on you.</Title><T style={s.small}>Collection guide · Sample notes with sources</T>{focus && <Pressable accessibilityRole="button" accessibilityLabel="Clear artwork focus" onPress={() => setFocus(undefined)} style={styles.focus}><T style={s.small}>Exploring {artwork(focus)?.title} · Tap to clear</T><Icon name="close" size={16}/></Pressable>}</View><ScrollView ref={scroll} contentContainerStyle={styles.messages} keyboardShouldPersistTaps="handled" onContentSizeChange={() => scroll.current?.scrollToEnd({ animated: false })}>
  {!messages.length ? <View style={styles.welcome}><View style={styles.spark}><Icon name="sparkles-outline" size={32} color={c.muted}/></View><T style={s.sectionTitle}>Every question opens a door.</T><T style={[s.muted, { textAlign: 'center' }]}>You don’t need the right words. Just a question, an observation, or a little curiosity.</T>{['Where should I start?', 'Tell me about Riverlight', 'I am interested in nature', 'Which rooms have step-free access?'].map(prompt => <Pressable key={prompt} accessibilityRole="button" onPress={() => ask(prompt)} style={styles.prompt}><T style={{ fontSize: 12 }}>{prompt}</T><Icon name="arrow-forward" size={16}/></Pressable>)}</View> : messages.map((m, index) => <View key={index} style={[styles.message, m.role === 'user' ? styles.userMessage : styles.guideMessage]}><T style={[styles.messageText, m.role === 'user' && { color: c.white }]}>{m.text}</T>{m.sources?.map((source, i) => <Pressable key={i} accessibilityRole={source.artworkId ? 'button' : 'text'} accessibilityLabel={source.title} disabled={!source.artworkId} onPress={() => source.artworkId && nav.navigate('Artwork', { id: source.artworkId })} style={styles.source}><Icon name="book-outline" size={13} color={c.muted}/><T style={styles.sourceText}>{source.title}</T></Pressable>)}</View>)}<Notice>This guide retrieves sample collection notes. Generative AI is not connected.</Notice></ScrollView><View style={styles.composer}><TextInput accessibilityLabel="Ask the guide" placeholder="What catches your curiosity?" placeholderTextColor={c.muted} value={question} onChangeText={setQuestion} onSubmitEditing={() => ask(question)} returnKeyType="send" maxLength={1000} style={styles.input}/><Pressable accessibilityRole="button" accessibilityLabel="Send question" accessibilityState={{ disabled: !question.trim() }} disabled={!question.trim()} onPress={() => ask(question)} style={[styles.send, !question.trim() && { opacity: .45 }]}><Icon name="arrow-up" color={c.white}/></Pressable></View></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({
  header: { paddingHorizontal: 22, paddingTop: 10, paddingBottom: 18, gap: 7, borderBottomWidth: 1, borderColor: c.border }, messages: { padding: 22, gap: 16, flexGrow: 1 }, welcome: { alignItems: 'center', gap: 18, paddingVertical: 12 }, spark: { width: 66, height: 66, backgroundColor: c.sage, alignItems: 'center', justifyContent: 'center', borderRadius: 22 }, prompt: { width: '100%', padding: 15, borderWidth: 1, borderColor: c.border, borderRadius: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: c.white }, message: { padding: 17, borderRadius: 16, maxWidth: '95%', gap: 12 }, userMessage: { alignSelf: 'flex-end', backgroundColor: c.green, borderBottomRightRadius: 3 }, guideMessage: { alignSelf: 'flex-start', backgroundColor: c.sage, borderTopLeftRadius: 3 }, messageText: { fontSize: 13, lineHeight: 22 }, source: { borderTopWidth: 1, borderColor: '#CCD7BF', paddingTop: 12, flexDirection: 'row', gap: 7, minHeight: 44, alignItems: 'center' }, sourceText: { fontSize: 10, lineHeight: 16, color: c.muted, flex: 1 }, composer: { paddingHorizontal: 16, paddingVertical: 12, flexDirection: 'row', gap: 10, borderTopWidth: 1, borderColor: c.border, backgroundColor: c.bg }, input: { flex: 1, minHeight: 48, backgroundColor: c.white, borderRadius: 14, padding: 14, borderWidth: 1, borderColor: c.border, fontSize: 13, color: c.ink }, send: { width: 48, height: 48, borderRadius: 16, backgroundColor: c.green, alignItems: 'center', justifyContent: 'center' }, focus: { backgroundColor: c.sage, padding: 10, borderRadius: 10, flexDirection: 'row', justifyContent: 'space-between', gap: 8, minHeight: 44, alignItems: 'center' }
});
