import React, { useState } from 'react';
import { Image, KeyboardAvoidingView, Platform, ScrollView, Share, Switch, TextInput, View } from 'react-native';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import * as ImagePicker from 'expo-image-picker';
import { artwork, artworks, sampleArtworks, interests, type RootStackParams } from '../model';
import { useStore } from '../store';
import { planRoute } from '../../../shared/domain.js';
import { ArtRow, Button, Chip, Empty, Eyebrow, Notice, Section, T, Title, c, s } from '../ui';

function ModalPage({ children }: { children: React.ReactNode }) { return <KeyboardAvoidingView style={{ flex: 1, backgroundColor: c.bg }} behavior={Platform.OS === 'ios' ? 'padding' : undefined} keyboardVerticalOffset={70}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled">{children}</ScrollView></KeyboardAvoidingView>; }
export function PlannerScreen({ navigation }: NativeStackScreenProps<RootStackParams, 'Planner'>) {
  const { state, dispatch } = useStore(); const initial = state.tour || state.preferences;
  const [duration, setDuration] = useState(initial.duration), [selected, setSelected] = useState(initial.interests), [stepFree, setStepFree] = useState(initial.stepFree);
  function plan() { dispatch({ type: 'plan', route: planRoute(sampleArtworks, { duration, interests: selected, stepFree }) }); navigation.popTo('Tour'); }
  return <ModalPage><Eyebrow>Your time, well wandered</Eyebrow><Title>A visit that{`\n`}feels like you.</Title><T style={s.muted}>A few starting points. We’ll leave room for discovery.</T><Section title="How long do you have?"/><View style={s.wrap}>{[15, 30, 45, 60, 90, 120].map(n => <Chip key={n} label={`${n} minutes`} active={duration === n} onPress={() => setDuration(n)}/>)}</View><Section title="What draws you in?"/><View style={s.wrap}>{interests.map(item => <Chip key={item} label={item} active={selected.includes(item)} onPress={() => setSelected(selected.includes(item) ? selected.filter(t => t !== item) : [...selected, item])}/>)}</View><View style={s.card}><View style={s.rowBetween}><View style={{ flex: 1, gap: 6 }}><T style={s.label}>Step-free route</T><T style={s.small}>Explore rooms without stairs.</T></View><Switch accessibilityLabel="Step-free route" value={stepFree} onValueChange={setStepFree} trackColor={{ true: c.green, false: c.border }}/></View></View><Notice icon="compass-outline">Routes use the sample room order and allow two minutes between works. Your active tour is saved on this device.</Notice>{state.tour && <Notice>Creating a new route replaces your current tour and its explored stops.</Notice>}<Button title="Find my route" icon="arrow-forward" onPress={plan}/></ModalPage>;
}

export function NativeLookupScreen() {
  const [photo, setPhoto] = useState<string | null>(null), [error, setError] = useState('');
  async function pick(camera: boolean) {
    setError('');
    try {
      if (camera) { const permission = await ImagePicker.requestCameraPermissionsAsync(); if (!permission.granted) { setError('Camera access was not granted. You can choose a photo or select an artwork below.'); return; } }
      const options: ImagePicker.ImagePickerOptions = { mediaTypes: ['images'], quality: .8, allowsEditing: false };
      const result = camera ? await ImagePicker.launchCameraAsync(options) : await ImagePicker.launchImageLibraryAsync(options);
      if (!result.canceled && result.assets[0]) setPhoto(result.assets[0].uri);
    } catch { setError('The camera or photo library is unavailable. You can still choose an artwork below.'); }
  }
  return <ModalPage><Title>Find the work{`\n`}in front of you.</Title><T style={s.muted}>Keep a photo as a reference, then choose its match from the collection.</T>{photo ? <Image source={{ uri: photo }} style={{ width: '100%', height: 250, borderRadius: 16 }} resizeMode="contain" accessibilityLabel="Your private artwork reference"/> : <Empty title="A closer look." body="Take a photo or choose one from your library."/>}<View style={s.row}><Button title="Take photo" secondary icon="camera-outline" style={{ flex: 1 }} onPress={() => { void pick(true); }}/><Button title="Photo library" secondary icon="images-outline" style={{ flex: 1 }} onPress={() => { void pick(false); }}/></View>{!!error && <Notice>{error}</Notice>}<Notice>Automatic image recognition is not connected. Your photo stays in this session and is not uploaded or stored with your visits.</Notice><Section title="Select the matching work"/><View>{artworks.map(art => <ArtRow key={art.id} art={art}/>)}</View></ModalPage>;
}

export function FeedbackScreen({ route, navigation }: NativeStackScreenProps<RootStackParams, 'Feedback'>) {
  const { dispatch } = useStore(); const id = route.params?.artworkId;
  const [type, setType] = useState('Accuracy'), [message, setMessage] = useState(''), [notice, setNotice] = useState('');
  const valid = message.trim().length >= 5;
  return <ModalPage><Title>Your perspective{`\n`}matters.</Title><T style={s.muted}>{id ? `A thought about ${artwork(id)?.title}.` : 'A thought, a correction, a new possibility.'}</T><View style={s.wrap}>{['Accuracy', 'Accessibility', 'Suggestion'].map(value => <Chip key={value} label={value} active={type === value} onPress={() => setType(value)}/>)}</View><TextInput accessibilityLabel="Your feedback" value={message} onChangeText={setMessage} multiline maxLength={2000} placeholder="Tell us what you noticed…" placeholderTextColor={c.muted} style={[s.input, { minHeight: 180, textAlignVertical: 'top' }]}/><Notice>Feedback is saved as a private draft on your device. Use Share to send it through an app of your choice; it is not sent to the museum automatically.</Notice>{!!notice && <Notice>{notice}</Notice>}<Button title="Save feedback draft" disabled={!valid} icon="bookmark-outline" onPress={() => { dispatch({ type: 'feedback', feedback: { id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, date: new Date().toISOString(), artworkId: id, type, message: message.trim() } }); navigation.goBack(); }}/><Button title="Share feedback" disabled={!valid} secondary icon="share-outline" onPress={() => { void Share.share({ message: `Unframe · ${type}${id ? ` · ${artwork(id)?.title}` : ''}\n\n${message.trim()}` }).catch(() => setNotice('Sharing is not available. You can save this draft instead.')); }}/></ModalPage>;
}

export function AboutScreen() { return <ModalPage><Eyebrow>Unframe for iPhone</Eyebrow><Title>A little more{`\n`}wonder.</Title><T>A personal museum companion, made for your pace and your perspective.</T><View style={s.card}><Section title="A sample world"/><T style={s.muted}>The main visit features a selection of real works from The Met and QAGOMA collections, with original introductory text. The floor plan, indoor marker and distances are demo data. The separate Northbank sample tour uses fictional works. All images are bundled for offline viewing.</T></View><View style={s.card}><Section title="Honest guidance"/><T style={s.muted}>The sample guide retrieves collection notes with sources. Web Scan and museum route planning connect to Google AI when the server is configured. AI interpretations are labelled; maps and indoor positions remain demonstrations.</T></View><View style={s.card}><Section title="Your device, your choice"/><T style={s.muted}>Bookmarks, preferences, active tours, visit reflections and feedback drafts stay on this device. Location is optional and checked on your device to identify whether you are near The Met or GOMA. Coordinates are not saved. On the web, capturing or uploading a photo in Scan sends it to the server and Google for matching. Opening the camera alone sends no photo. Unframe does not retain visitor photos. Native photo lookup remains a temporary local reference.</T></View><Notice icon="business-outline">The museum management workspace remains in the web project. This mobile prototype has its own on-device data; collection edits and visitor data do not sync with the website.</Notice><T style={s.small}>Unframe · Mobile prototype 1.0.0{`\n`}Inspired by self-directed, location-aware museum experiences.</T></ModalPage>; }
